// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import TRealsController from "./t_reals_controller"
application.register("t-reals", TRealsController)

import TrustedByController from "./trusted_by_controller"
application.register("trusted-by", TrustedByController)

import ScrollToSection from "./scroll_to_section_controller"
application.register("scroll-to-section", ScrollToSection)

import Navbar from "./navbar_controller"
application.register("navbar", Navbar)
